Feature add oauth
bleachjade/Kvent pull request #19
Opened 2020-11-11 16:12 UTC by JirawadeeSampusri

I have already done Oauth google but the secret key of Oauth can't be hidden and I also try to use Config but it doesn't work.
For the Logout button is on the profile page.

2020-11-13 07:36 UTC, bleachjade requested changes

2020-11-13 07:36 UTC, bleachjade commented on Kvent/forms.py
> +
delete this

2020-11-13 07:36 UTC, bleachjade commented on Kvent/templates/kvent/profile.html
> +            {% endif %}
You should also add this button in the index and don't forget to parse it inside <li> tag

2020-11-13 07:36 UTC, bleachjade commented on Kvent/templates/kvent/profile.html
> +
delete unnecessary space

2020-11-13 07:36 UTC, bleachjade commented on Kvent/templates/registration/createaccount.html
> +
What is this used for? if it did not use in any of our code, please delete it

2020-11-13 07:36 UTC, bleachjade commented on Kvent/templates/registration/login.html
> +     </a>
keep this button but the rest of it just use the template in the develop branch

2020-11-13 07:41 UTC, bleachjade requested changes

2020-11-13 07:41 UTC, bleachjade commented on mysite/settings.py
> +SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'QjQaLqQFiP_Hmgfv3lPCr9sJ'
please try to add it in .env and use config, we should not push the secret key to our repo

2020-11-13 07:41 UTC, bleachjade commented on mysite/settings.py
> +STATIC_URL = '/static/'
delete this, we already have a STATIC_URL above

2020-11-13 07:41 UTC, bleachjade commented on mysite/urls.py
>      # path('accounts/', include('django.contrib.auth.urls')),
delete comment line out

2020-11-13 07:42 UTC, bleachjade requested changes
**Don't include the files in the api folder!** When you doing a google auth, you just add auth things in the setting not creating a new manage.py and others file

2020-11-15 08:00 UTC, forfeen commented on Kvent/templates/kvent/profile.html
> +                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
Please place the logout button at the right of profile page.

2020-11-15 11:12 UTC, merged